env:
  GOOGLE_CHAT_WEBHOOK_URL: ""

resources:
  requests:
    memory: "128Mi"
    cpu : "1"
  limits:
    memory: "128Mi"
    cpu: "1"

image:
  repository: sawn37/kube-alert-action
  tag: latest

service:
  port: 8000
  annotations: {}
  type: LoadBalancer
