apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: webhook
              containerPort: 8000
          {{- if .Values.env.GOOGLE_CHAT_WEBHOOK_URL }}
          env:
          - name: GOOGLE_CHAT_WEBHOOK_URL
            value: {{ .Values.env.GOOGLE_CHAT_WEBHOOK_URL  | quote }}
          {{- end}}
          {{- if .Values.resources  }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
