apiVersion: v1
kind: Service
metadata:
  name: kube-alert-action
  namespace: kube-alert-action
spec:
  type: LoadBalancer
  selector:
    app: kube-alert-action
  ports:
    - name: webhook
      port: 8000
      targetPort: 8000
      protocol: TCP
